# -*- coding: utf-8 -*-
"""
SheetReady — product landing-page data for build_pages.py.

Each product dict drives ONE page at /templates/<name>/index.html.
Keys:
  name      URL folder name (also internal id)
  slug      Gumroad product slug  ->  https://supunsandeep.gumroad.com/l/<slug>
  price     "0" | "19" | "24"  (STRING; "0" is the free product)
  cat       short category label shown in the breadcrumb-adjacent kicker
  title     <title>
  meta      <meta name=description>
  h1        the single <h1>
  ld_desc   unique 1-2 sentence Product JSON-LD description (truthful)
  sections  list of {"h2","body"} -> rendered <section><h2>..</h2><p>..</p>
  includes  list of "What's included" bullets (5-8)
  faq       list of {"q","a"}  (3-4)
  related   list of names (URL folders) to cross-link (2-3)
  related_intro  sentence that introduces the related links
"""

PRODUCTS = [
    # ------------------------------------------------------------------ 1 FREE
    {
        "name": "free-money-tracker",
        "slug": "jvtmti",
        "price": "0",
        "cat": "Personal",
        "title": "Free Monthly Money Tracker — Google Sheets Template",
        "meta": "Download our free monthly money tracker for Google Sheets and Excel. No signup needed. Log income, spending, and savings in one simple spreadsheet.",
        "h1": "Free Monthly Money Tracker for Google Sheets and Excel",
        "ld_desc": "A free monthly money tracker that logs your income and spending in one place and shows your running balance and savings rate without any setup.",
        "intro": "The Simple Monthly Money Tracker is the easiest way to see where your money actually goes. Type your income and expenses into the labelled cells and the running balance, category totals, and savings rate update on their own. It is completely free and works in both Google Sheets and Microsoft Excel.",
        "sections": [
            {"h2": "What the Free Money Tracker Includes",
             "body": "The tracker gives you a single income-and-expense log with a small dashboard on top. You enter each amount once, choose a category, and the sheet sums your spending, subtracts it from your income, and shows what is left for the month. There is a savings-rate cell that tells you what share of your income you kept, and a simple month summary so you do not have to add anything up by hand."},
            {"h2": "How to Use the Monthly Money Tracker",
             "body": "Open the file in Google Sheets (File then Make a copy) or in Excel, and start with your income for the month. Then log expenses as they happen, picking a category from the list. The dashboard recalculates instantly, so by the end of the month you can see your biggest spending categories and exactly how much you saved. There is nothing to install and no formulas to write."},
            {"h2": "Start Tracking Your Money Today — Free Download",
             "body": "Because it is free, the money tracker is the best way to try the SheetReady style before buying anything. If you outgrow it and want budget-vs-actual columns, multiple months, or savings goals, the paid budget planner and savings tracker pick up where this leaves off. Add it on Gumroad at no cost and download it in seconds."},
        ],
        "includes": [
            "A single income and expense log — type once, categorised automatically",
            "Running monthly balance so you always know what is left",
            "Automatic savings-rate cell (what share of income you kept)",
            "Pre-built category totals — no SUM formulas to write yourself",
            "A clean month-summary dashboard at the top of the sheet",
            "Works in Google Sheets and Microsoft Excel with no add-ons",
            "Fully editable — rename categories to match how you spend",
        ],
        "faq": [
            {"q": "Is the money tracker really free?",
             "a": "Yes. Add it on Gumroad at a price of $0 and download it instantly — there is no charge and no card required. You can enter your email if you would like the occasional spreadsheet tip, but it is not required to get the file."},
            {"q": "Do I need a Google account to use it?",
             "a": "You need a Google account only if you want to use it in Google Sheets, where you choose File then Make a copy to get your own editable version. If you prefer Excel, open the downloaded file directly — no account needed."},
            {"q": "Will my numbers be private?",
             "a": "Yes. The tracker is just a spreadsheet file that lives in your own Google Drive or on your own computer. Nothing you type is sent anywhere, and SheetReady never sees your figures."},
            {"q": "What is the difference between this and the paid budget planner?",
             "a": "This free tracker logs what you actually spent. The paid Monthly Budget Planner adds a planned budget for each category, budget-vs-actual columns, and an automatic savings rate, so you can plan ahead rather than only look back."},
        ],
        "related_intro": "Ready for more? These paid templates build on the free tracker:",
        "related": ["monthly-budget-planner", "savings-goal-tracker", "debt-payoff-tracker"],
    },
    # ------------------------------------------------------------------ 2
    {
        "name": "monthly-budget-planner",
        "slug": "kbpell",
        "price": "19",
        "cat": "Personal",
        "title": "Monthly Budget Planner — Budget vs Actual + Savings Rate",
        "meta": "Track every dollar with a monthly budget planner that shows budget vs actual spending and your savings rate automatically. For Google Sheets and Excel.",
        "h1": "Monthly Personal Budget Planner — Budget vs Actual with Savings Rate",
        "ld_desc": "A monthly personal budget planner with budget-vs-actual columns and an automatic savings rate, so you can plan each category and see exactly where the month went off track.",
        "intro": "The Monthly Personal Budget Planner turns the guesswork out of budgeting. You set a planned amount for each category, log what you actually spend, and the planner shows the difference and your savings rate without any manual maths. It works in both Google Sheets and Microsoft Excel.",
        "sections": [
            {"h2": "See Exactly Where Your Money Goes Each Month",
             "body": "The planner groups your spending into clear categories — housing, food, transport, subscriptions, and anything you add — and totals each one as you type. A summary at the top shows total income, total spending, and what is left, so you can see at a glance whether the month is on track or running tight."},
            {"h2": "Built-In Budget vs Actual Columns — No Manual Math",
             "body": "For every category you enter a planned budget and your actual spend side by side. The planner calculates the variance automatically and flags where you went over, so you can adjust next month instead of wondering what happened. There are no formulas to build — the columns are already wired up."},
            {"h2": "Your Savings Rate Calculated Automatically",
             "body": "Your savings rate — the share of income you did not spend — is one of the most useful numbers in personal finance, and the planner works it out for you each month. Watching that single percentage is often more motivating than tracking dozens of line items, and it updates the moment you change a figure."},
            {"h2": "Works in Google Sheets and Microsoft Excel",
             "body": "Use whatever you already have. Open the file in Excel, or choose File then Make a copy to use it in Google Sheets. The categories, formulas, and dashboard behave the same way in both, with no plugins or add-ons required."},
        ],
        "includes": [
            "Planned budget and actual spend columns for every category",
            "Automatic budget-vs-actual variance for each line",
            "Monthly summary: total income, total spending, money left",
            "Automatic savings-rate calculation",
            "Editable category list to match how you actually spend",
            "Clean dashboard view at the top of the sheet",
            "Works identically in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "What is the difference between a budget planner and a money tracker?",
             "a": "A money tracker records what you already spent. A budget planner adds a plan: you set a target for each category first, then compare it against what you actually spent. That budget-vs-actual view is what lets you change behaviour rather than just review it."},
            {"q": "Can I use this as a zero-based budget?",
             "a": "Yes. Because you assign a planned amount to every category and the planner totals them against your income, you can give every dollar a job and aim for zero left unassigned — the classic zero-based approach."},
            {"q": "How is the savings rate calculated?",
             "a": "The planner divides the money you did not spend by your total income for the month and shows it as a percentage. You do not have to enter or calculate anything — it updates automatically as you log income and expenses."},
            {"q": "Do I need to know spreadsheet formulas?",
             "a": "No. Every formula is already built in. You only type your numbers into the labelled cells, and the totals, variances, and savings rate calculate on their own."},
        ],
        "related_intro": "Pairs well with these SheetReady templates:",
        "related": ["free-money-tracker", "savings-goal-tracker", "debt-payoff-tracker"],
    },
    # ------------------------------------------------------------------ 3
    {
        "name": "debt-payoff-tracker",
        "slug": "spwlfb",
        "price": "19",
        "cat": "Personal",
        "title": "Debt Payoff Tracker — Snowball & Avalanche Google Sheets",
        "meta": "Use the Snowball or Avalanche method to pay off debt faster. This Google Sheets tracker calculates your payoff date and total interest saved automatically.",
        "h1": "Debt Payoff Tracker — Snowball and Avalanche Method for Google Sheets",
        "ld_desc": "A debt payoff tracker that compares the snowball and avalanche methods, projects your debt-free date, and shows the total interest you will save.",
        "intro": "The Debt Payoff Tracker helps you clear credit cards, loans, and any other balance faster by giving you a clear plan. Enter your debts and your monthly payment, choose the snowball or avalanche method, and the tracker projects your debt-free date and the interest you will save. It works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Choose Your Strategy: Debt Snowball or Debt Avalanche",
             "body": "The tracker supports both of the popular payoff strategies and lets you compare them side by side. You list every debt with its balance, interest rate, and minimum payment, then decide how much extra you can put toward debt each month. The sheet handles the ordering and the maths for whichever method you pick."},
            {"h2": "How the Debt Snowball Method Works",
             "body": "The snowball method pays the smallest balance first while paying minimums on the rest, then rolls that freed-up payment onto the next-smallest debt. It is the method many people stick with because each balance you fully clear is a visible win. The tracker shows how quickly those wins add up."},
            {"h2": "How the Debt Avalanche Method Saves More Interest",
             "body": "The avalanche method targets the debt with the highest interest rate first, which mathematically costs you the least in total interest. The tracker calculates exactly how much interest the avalanche order saves compared with the snowball order, so you can make an informed choice between the cheaper plan and the more motivating one."},
            {"h2": "Track Credit Cards, Student Loans, and Any Debt",
             "body": "You can list any kind of debt — credit cards, a car loan, student loans, a personal loan, or money owed to family. Each one has its own row with balance, rate, and payment, and the tracker keeps a running total so you always know how much is left across everything."},
            {"h2": "See Your Debt-Free Date Before You Start",
             "body": "Before you make a single payment, the tracker projects the month you will be debt-free based on your chosen method and extra payment. Increase the extra amount and watch the date move closer — it is a clear way to see the payoff of finding a little more room in your budget."},
        ],
        "includes": [
            "One row per debt with balance, interest rate, and minimum payment",
            "Snowball and avalanche ordering, switchable",
            "Projected debt-free date for your chosen plan",
            "Total interest paid and interest saved comparison",
            "Running total of remaining debt across all accounts",
            "Extra-payment input so you can model paying more",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "Snowball vs avalanche — which should I use?",
             "a": "Avalanche saves the most interest because it targets your highest rate first. Snowball clears small balances first for quick motivation. The tracker shows both side by side, so you can see the interest difference and pick the plan you will actually stick to."},
            {"q": "Does it calculate my debt-free date automatically?",
             "a": "Yes. Based on your balances, interest rates, minimum payments, and any extra you add, the tracker projects the month you will be debt-free. Change the extra payment and the date updates immediately."},
            {"q": "Can I track more than one credit card?",
             "a": "Yes. You can list as many debts as you like — credit cards, student loans, car loans, personal loans — each on its own row, and the tracker totals them and orders them for your chosen method."},
            {"q": "Does it work in Excel as well as Google Sheets?",
             "a": "Yes. The tracker opens in Microsoft Excel and imports into Google Sheets, and the calculations behave the same in both."},
        ],
        "related_intro": "Build a full plan with these SheetReady templates:",
        "related": ["monthly-budget-planner", "savings-goal-tracker", "free-money-tracker"],
    },
    # ------------------------------------------------------------------ 4
    {
        "name": "savings-goal-tracker",
        "slug": "uxktm",
        "price": "19",
        "cat": "Personal",
        "title": "Savings Goal Tracker — Google Sheets & Excel Template",
        "meta": "Track multiple savings goals and sinking funds in one place. See your progress and know exactly when you will hit each target. Works in Sheets and Excel.",
        "h1": "Savings Goal & Net-Worth Tracker — Multiple Goals and Sinking Funds",
        "ld_desc": "A savings tracker that follows multiple goals and sinking funds at once, shows progress toward each target, and tracks your net worth over time.",
        "intro": "The Savings Goal & Net-Worth Tracker keeps all of your savings goals in one place — an emergency fund, a holiday, a car, a deposit — and shows how close each one is. Set a target and a date, log your contributions, and the tracker tells you the monthly amount needed and your overall net worth. It works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Track Multiple Savings Goals at Once",
             "body": "Most savings tools only handle one goal. This tracker lets you run several side by side, each with its own target, current balance, and progress bar. You can see at a glance which goals are ahead, which are behind, and how much you have saved across all of them."},
            {"h2": "Built-In Sinking Funds Dashboard",
             "body": "A sinking fund is money you set aside a little at a time for a known future cost — insurance, holidays, car repairs. The tracker has a dedicated dashboard for these, so irregular bills stop being a shock. You decide what to save each month and the sheet keeps the balances tidy."},
            {"h2": "Watch Your Net Worth Grow Over Time",
             "body": "Beyond individual goals, the tracker adds up your savings and balances into a single net-worth figure you can update each month. Seeing that number rise over time is one of the most motivating things in personal finance, and the tracker plots it for you without any manual calculation."},
            {"h2": "Set a Target Date and See the Monthly Amount Needed",
             "body": "For each goal you enter how much you need and when you want it. The tracker works backward to show the monthly contribution required to hit the target on time, so a vague wish becomes a concrete plan you can budget for."},
        ],
        "includes": [
            "Multiple savings goals tracked side by side",
            "Progress bar and percentage complete for each goal",
            "Dedicated sinking-funds dashboard for irregular costs",
            "Automatic monthly amount needed to hit each target on time",
            "Running net-worth figure updated as you log balances",
            "Editable goal names, targets, and dates",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "What is a sinking fund?",
             "a": "A sinking fund is money you save gradually for a known future expense — like car insurance, holidays, or repairs — so the bill does not blow up your budget when it arrives. The tracker has a dashboard built specifically for managing these."},
            {"q": "Can I track more than one goal at a time?",
             "a": "Yes. That is the point of this tracker — you can run an emergency fund, a holiday, a deposit, and more at the same time, each with its own target, progress bar, and date."},
            {"q": "How does it know my monthly amount needed?",
             "a": "You enter the target amount and the date you want to reach it. The tracker divides the remaining amount by the months left, so you always see the contribution required to stay on schedule."},
            {"q": "Is this the same as a budget planner?",
             "a": "No. A budget planner manages your month-to-month income and spending. This tracker focuses on longer-term goals and your net worth. Many people use both — the budget frees up money each month, and this tracker shows where it is going."},
        ],
        "related_intro": "Works alongside these SheetReady templates:",
        "related": ["monthly-budget-planner", "free-money-tracker", "debt-payoff-tracker"],
    },
    # ------------------------------------------------------------------ 5
    {
        "name": "13-week-cash-flow",
        "slug": "xfitf",
        "price": "24",
        "cat": "Business",
        "title": "13-Week Cash Flow Forecast — Excel & Google Sheets",
        "meta": "Plan your next quarter week by week. A 13-week cash flow forecast template for Excel and Google Sheets — rolling forecast and runway view included.",
        "h1": "13-Week Cash Flow Forecast Template for Small Business",
        "ld_desc": "A 13-week cash flow forecast that projects cash in and cash out week by week, gives a rolling view of your runway, and flags shortfalls before they happen.",
        "intro": "The 13-Week Cash Flow Forecast is the tool finance teams use to see trouble coming. You plan expected cash in and cash out for each of the next thirteen weeks, and the template shows your projected closing balance every week, so a shortfall is visible weeks before it lands. It works in Excel and Google Sheets.",
        "sections": [
            {"h2": "Rolling 13-Week View — Know Your Runway Before It's Gone",
             "body": "Thirteen weeks is one quarter — long enough to plan around, short enough to forecast with confidence. The template lays out every week in columns, totals your expected inflows and outflows, and carries the closing balance forward so you can see exactly when cash gets tight. As each week passes you roll the model forward and always keep a quarter of visibility ahead."},
            {"h2": "Who Uses a 13-Week Cash Flow Model?",
             "body": "This is a standard tool for small-business owners, finance managers, and anyone steering a company through a tight stretch. It is widely used in turnaround and lending situations precisely because it focuses on actual cash timing rather than profit on paper. If payroll, rent, or supplier payments ever feel like a juggling act, this model brings order to it."},
            {"h2": "Excel and Google Sheets — Download Instantly",
             "body": "The forecast opens in Microsoft Excel and imports into Google Sheets, with the week columns and running-balance formulas already built. There is nothing to install. Buy it through secure Gumroad checkout and the file is on screen and in your inbox in seconds."},
        ],
        "includes": [
            "Thirteen weekly columns covering a full quarter",
            "Separate cash-in and cash-out sections you can label",
            "Automatic weekly closing balance carried forward",
            "Running runway view that flags the week cash turns negative",
            "Opening-balance input so the forecast starts from reality",
            "Designed to roll forward each week as actuals come in",
            "Works in Microsoft Excel and Google Sheets",
        ],
        "faq": [
            {"q": "Why 13 weeks specifically?",
             "a": "Thirteen weeks is exactly one quarter. It is short enough that your week-by-week estimates stay realistic, but long enough to spot and plan around a cash shortfall before it arrives — which is why it is the standard horizon for short-term cash forecasting."},
            {"q": "Is this different from a profit and loss statement?",
             "a": "Yes. A P&L shows profit on paper, which can look healthy even when your bank balance is about to run dry because of payment timing. A 13-week cash flow forecast tracks actual cash in and out by week, so it shows the timing problems a P&L hides."},
            {"q": "What does rolling the forecast forward mean?",
             "a": "Each week you replace the oldest week's estimates with what actually happened and add a new week at the far end. That keeps a full quarter of forward visibility at all times, which is the real value of the model."},
            {"q": "Does it work in Google Sheets?",
             "a": "Yes. It opens in Excel and imports into Google Sheets, and the weekly formulas and running balance work the same in both."},
        ],
        "related_intro": "Manage the rest of your business cash with these templates:",
        "related": ["cash-flow-profit-dashboard", "invoice-tracker", "expense-tax-tracker"],
    },
    # ------------------------------------------------------------------ 6
    {
        "name": "invoice-tracker",
        "slug": "jwehbb",
        "price": "24",
        "cat": "Business",
        "title": "Automated Invoice Tracker — Google Sheets Template",
        "meta": "Track sent, paid, and overdue invoices in one place. Invoice tracker for Google Sheets — includes invoice generator, client log, and payment dashboard.",
        "h1": "Automated Invoice Tracker & Generator for Google Sheets",
        "ld_desc": "An invoice tracker and generator that records every invoice as sent, paid, or overdue, keeps a client log, and shows outstanding amounts on a payment dashboard.",
        "intro": "The Automated Invoice Tracker & Generator keeps your invoicing under control in one spreadsheet. Log each invoice once and the tracker shows what is sent, what is paid, and what is overdue, with the totals on a payment dashboard. It includes a simple invoice layout and a client log, and works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Never Chase an Overdue Invoice Again",
             "body": "Each invoice gets a row with its amount, the date sent, the due date, and its status. The tracker automatically flags anything past its due date as overdue, so the invoices that need chasing rise to the top instead of slipping through the cracks. You can see your total outstanding and your total overdue at a glance."},
            {"h2": "Built for Freelancers and Small Businesses",
             "body": "If invoicing software feels like overkill for the number of clients you have, this spreadsheet is the middle ground. It is light enough to open and update in seconds, but organised enough that you always know who owes you, how much, and for how long — without paying a monthly subscription for the privilege."},
            {"h2": "What's Included: Generator + Tracker + Dashboard",
             "body": "There are three parts that work together: a clean invoice layout you can fill in and send, a tracker where each invoice is logged and its status updates automatically, and a dashboard that totals paid, outstanding, and overdue amounts. Together they cover the whole cycle from issuing an invoice to getting paid."},
        ],
        "includes": [
            "Fill-in invoice layout you can complete and send",
            "Invoice log with amount, date sent, due date, and status",
            "Automatic overdue flagging based on the due date",
            "Payment dashboard: total paid, outstanding, and overdue",
            "Simple client log to keep contact details in one place",
            "Status colour cues so the list is easy to scan",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "Can this create invoices, or only track them?",
             "a": "Both. There is a fill-in invoice layout you can complete and send, plus a tracker that logs every invoice and a dashboard that totals what is paid, outstanding, and overdue."},
            {"q": "How does it know which invoices are overdue?",
             "a": "You enter each invoice's due date and mark it paid when payment arrives. Anything still unpaid past its due date is automatically flagged as overdue, so the invoices that need a follow-up stand out."},
            {"q": "Is this good for freelancers?",
             "a": "Yes. It is built for freelancers and small businesses who find full invoicing software more than they need. It is fast to update and has no monthly fee."},
            {"q": "Does it work in Google Sheets?",
             "a": "Yes. It opens in Excel and imports into Google Sheets, and the status flags and dashboard totals work the same in both."},
        ],
        "related_intro": "Keep the money side organised with these templates:",
        "related": ["13-week-cash-flow", "cash-flow-profit-dashboard", "crm-sales-pipeline"],
    },
    # ------------------------------------------------------------------ 7
    {
        "name": "freelancer-tax-estimator",
        "slug": "mzwow",
        "price": "24",
        "cat": "Freelance",
        "title": "Freelancer Income & Tax Estimator — Google Sheets",
        "meta": "Estimate your quarterly taxes as a freelancer. Track income, deductible expenses, and tax owed — Google Sheets template, instant download.",
        "h1": "Freelancer Income Tax Estimator Spreadsheet",
        "ld_desc": "A freelancer tax estimator that tracks income and deductible expenses, estimates quarterly tax owed, and shows how much to set aside from each payment.",
        "intro": "The Freelancer Income & Tax Estimator takes the surprise out of tax season. Log your income and deductible expenses, set your tax rate, and the spreadsheet estimates what you owe and how much to set aside from each payment. It is built for 1099 contractors and the self-employed, and works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Calculate Quarterly Estimated Tax Payments",
             "body": "Freelancers usually pay tax in quarterly instalments rather than once a year. The estimator adds up your income and expenses for each period, applies your tax rate, and shows the estimated payment for the quarter, so you can put the right amount aside in advance instead of scrambling at the deadline."},
            {"h2": "Track Every Write-Off Before Tax Season",
             "body": "Every deductible expense you log lowers your estimated tax, so the spreadsheet doubles as a running record of write-offs. Capture software, equipment, mileage, home-office costs, and fees as they happen, and you reach tax time with a tidy total instead of a shoebox of receipts."},
            {"h2": "Works for 1099 Contractors and Self-Employed Freelancers",
             "body": "Whether you freelance full time or run a side business, the estimator adapts to you — set your own tax rate and categories to match your situation. It gives you a realistic picture of your after-tax income, which is far more useful for planning than the gross figure on your invoices. Please treat it as a planning estimate, not formal tax advice."},
        ],
        "includes": [
            "Income log across the year and by quarter",
            "Deductible-expense tracker with editable categories",
            "Adjustable tax-rate input for your situation",
            "Estimated quarterly tax payment calculation",
            "Set-aside amount shown per payment received",
            "After-tax income view for realistic planning",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "How much should a freelancer set aside for taxes?",
             "a": "A common rule of thumb is 25–30% of income, but it depends on your country, total income, and deductions. This spreadsheet lets you set your own rate and then shows the exact amount to set aside from each payment based on your real numbers."},
            {"q": "Does it calculate quarterly estimated payments?",
             "a": "Yes. It groups your income and expenses by quarter, applies your tax rate, and shows the estimated payment for each period so you are not surprised at the deadline."},
            {"q": "Is this tax advice?",
             "a": "No. It is a planning tool that helps you estimate and set money aside. Tax rules vary by country and situation, so check the figures against your local rules or an accountant before filing."},
            {"q": "Will it work for 1099 contractors?",
             "a": "Yes. It is designed for 1099 contractors and self-employed freelancers, and you can set the tax rate and expense categories to match how you work."},
        ],
        "related_intro": "Stay on top of the business side with these templates:",
        "related": ["expense-tax-tracker", "invoice-tracker", "digital-product-sales-tracker"],
    },
    # ------------------------------------------------------------------ 8
    {
        "name": "expense-tax-tracker",
        "slug": "ybnibo",
        "price": "19",
        "cat": "Business",
        "title": "Business Expense & Tax Deduction Tracker — Sheets",
        "meta": "Capture every tax write-off automatically. Google Sheets expense tracker for the self-employed, freelancers, and small businesses. Home office and mileage.",
        "h1": "Business Expense & Tax Deduction Tracker for Google Sheets",
        "ld_desc": "A business expense tracker that categorises every spend, captures deductible write-offs like home office and mileage, and totals them ready for tax season.",
        "intro": "The Business Expense & Tax Deduction Tracker makes sure no write-off slips away. Log each expense once, choose a deduction category, and the tracker totals your deductibles by category and for the whole year. It is built for the self-employed, freelancers, and small businesses, and works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Track Every Write-Off — Home Office, Mileage, Subscriptions",
             "body": "The tracker comes with common deduction categories already set up — home office, mileage, software and subscriptions, equipment, professional fees, and more. You log an expense, pick its category, and it rolls up into your year-end totals automatically, so the deductible amounts are ready when you need them."},
            {"h2": "Self-Employed and Freelancer Deduction Categories",
             "body": "Deductions are where self-employed people most often leave money on the table, simply because the spending was never recorded. By giving every business cost a home and a category, the tracker turns scattered receipts into a clear list of write-offs you can actually claim. You can rename or add categories to fit your trade."},
            {"h2": "Year-End Tax Prep in One Click",
             "body": "When tax time comes, the work is already done: the tracker shows your total deductible expenses by category and overall, so you or your accountant can pull the numbers straight from the sheet. No adding up receipts, no guessing — just a tidy summary of a full year of spending. Treat the categories as a starting point and confirm what is deductible in your area."},
        ],
        "includes": [
            "Pre-built deduction categories (home office, mileage, software, fees)",
            "One-line-per-expense log with date, amount, and category",
            "Automatic deductible totals by category and for the year",
            "Editable categories to match your trade",
            "Notes column for receipts or context",
            "Clean year-end summary for tax prep",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "What expenses can I deduct as self-employed?",
             "a": "Common write-offs include home-office costs, mileage, software and subscriptions, equipment, and professional fees — all of which the tracker has categories for. Exact rules vary by country, so confirm what qualifies in your area or with an accountant."},
            {"q": "Can I track mileage and home-office costs?",
             "a": "Yes. Both are built-in categories, along with software, equipment, and professional fees, and you can add your own categories to match how your business spends."},
            {"q": "Does it total my deductions for tax time?",
             "a": "Yes. As you log expenses the tracker totals your deductibles by category and for the whole year, so the figures are ready to hand to you or your accountant at tax time."},
            {"q": "Does it work in Google Sheets?",
             "a": "Yes. It opens in Excel and imports into Google Sheets, and the category totals work the same in both."},
        ],
        "related_intro": "Pair it with these freelance and business templates:",
        "related": ["freelancer-tax-estimator", "invoice-tracker", "cash-flow-profit-dashboard"],
    },
    # ------------------------------------------------------------------ 9
    {
        "name": "inventory-reorder",
        "slug": "hzcos",
        "price": "24",
        "cat": "Business",
        "title": "Inventory Reorder Manager — Etsy Shop & Small Business",
        "meta": "Never run out of stock. Tracks inventory levels, calculates reorder points, and flags low stock — Google Sheets and Excel, built for Etsy sellers.",
        "h1": "Inventory & Reorder Manager Spreadsheet for Etsy Shops",
        "ld_desc": "An inventory and reorder manager that tracks stock levels, calculates reorder points, and flags low stock so product sellers never run out of bestsellers.",
        "intro": "The Inventory & Reorder Manager keeps your shop in stock without the guesswork. Track quantity on hand for every product, set a reorder point, and the spreadsheet flags items that are running low so you can restock before you sell out. It is built for Etsy sellers, crafters, and small product businesses, and works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Automatic Reorder Point Calculator",
             "body": "For each product you enter how fast it sells and how long restocking takes, and the spreadsheet calculates the reorder point — the stock level at which you should order more. That turns restocking from a guess into a number, so you order at the right time rather than too early or too late."},
            {"h2": "Low Stock Alerts — Know Before You Run Out",
             "body": "When an item's quantity on hand drops to or below its reorder point, the spreadsheet flags it clearly, so low-stock products rise to your attention instead of quietly selling out. A summary shows how many SKUs need reordering right now, so a quick glance tells you what to buy."},
            {"h2": "Built for Etsy Sellers, Crafters, and Product Businesses",
             "body": "If you sell physical products — handmade goods, print-on-demand stock, resale items — this manager scales with your catalogue. Every product gets a row with its cost, price, and stock level, so you can keep tabs on dozens or hundreds of SKUs in one place without expensive inventory software."},
        ],
        "includes": [
            "One row per product (SKU) with cost, price, and stock on hand",
            "Reorder-point calculation from sales speed and lead time",
            "Automatic low-stock flag when you hit the reorder point",
            "Summary of how many SKUs need reordering now",
            "Stock value totals for your whole catalogue",
            "Editable for any number of products",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "What is a reorder point?",
             "a": "A reorder point is the stock level at which you should place a new order, calculated from how fast an item sells and how long restocking takes. The spreadsheet works it out for each product so you restock at the right moment."},
            {"q": "Is this suitable for an Etsy shop?",
             "a": "Yes. It is built with Etsy sellers, crafters, and small product businesses in mind, and it handles anything from a handful of items to a large catalogue of SKUs."},
            {"q": "How do the low-stock alerts work?",
             "a": "When a product's quantity on hand falls to or below its reorder point, the sheet flags it and counts it in a reorder summary, so the items you need to buy stand out immediately."},
            {"q": "Does it work in Google Sheets?",
             "a": "Yes. It opens in Excel and imports into Google Sheets, with the reorder calculations and flags working the same in both."},
        ],
        "related_intro": "Run the rest of your shop with these templates:",
        "related": ["digital-product-sales-tracker", "cash-flow-profit-dashboard", "crm-sales-pipeline"],
    },
    # ------------------------------------------------------------------ 10
    {
        "name": "crm-sales-pipeline",
        "slug": "syqunq",
        "price": "24",
        "cat": "Sales",
        "title": "Simple CRM & Sales Pipeline — Google Sheets",
        "meta": "Manage clients and close deals without expensive software. A simple CRM Google Sheets template for freelancers, coaches, and small businesses.",
        "h1": "Simple CRM & Sales Pipeline Template for Google Sheets",
        "ld_desc": "A simple CRM and sales pipeline that keeps every client and lead in one place and moves deals through clear stages from first contact to closed.",
        "intro": "The Simple CRM & Sales Pipeline keeps your clients and deals organised without a monthly software bill. Log each lead, record contact details and notes, and move deals through clear stages from first contact to closed. It is built for freelancers, virtual assistants, coaches, and consultants, and works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Client Management Without the Software Subscription",
             "body": "A dedicated CRM is overkill — and an ongoing cost — when you have a manageable list of clients. This spreadsheet gives you the essentials: a single place for names, contact details, notes, and the status of every relationship, so nothing falls through the cracks and you owe no one a monthly fee."},
            {"h2": "Track Every Lead from First Contact to Closed Deal",
             "body": "Each lead moves through stages you can see at a glance — new, in conversation, quoted, won, or lost. The pipeline view shows how many deals sit at each stage and their value, so you know whether you have enough in the works to hit your goals and where deals are getting stuck."},
            {"h2": "For Freelancers, VAs, Coaches, and Consultants",
             "body": "If your business runs on relationships and follow-ups, this template keeps them on track. Log when you last spoke to someone and what you agreed, so a quick scan reminds you who to follow up with and when — the small, consistent habit that turns leads into clients."},
        ],
        "includes": [
            "Single client list with names, contacts, and notes",
            "Pipeline stages from first contact to won or lost",
            "Deal value per lead and totals by stage",
            "Last-contacted and follow-up columns",
            "At-a-glance view of how many deals sit at each stage",
            "Editable stages and fields to match your process",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "Do I really need CRM software, or is a spreadsheet enough?",
             "a": "If you have a manageable number of clients, a well-structured spreadsheet covers the essentials — contacts, notes, and deal stages — without a monthly subscription. This template gives you that, and you can always move to software later if you outgrow it."},
            {"q": "Can I customise the pipeline stages?",
             "a": "Yes. The stages and fields are fully editable, so you can match the steps your own sales process actually uses."},
            {"q": "Who is this template for?",
             "a": "It is built for freelancers, virtual assistants, coaches, and consultants — anyone whose business runs on client relationships and follow-ups rather than a high volume of transactions."},
            {"q": "Does it work in Google Sheets?",
             "a": "Yes. It opens in Excel and imports into Google Sheets, and the pipeline view and totals work the same in both."},
        ],
        "related_intro": "Keep the rest of the business running with these templates:",
        "related": ["invoice-tracker", "cash-flow-profit-dashboard", "digital-product-sales-tracker"],
    },
    # ------------------------------------------------------------------ 11
    {
        "name": "cash-flow-profit-dashboard",
        "slug": "khtvuw",
        "price": "19",
        "cat": "Business",
        "title": "Monthly Cash Flow & Profit Dashboard — Google Sheets",
        "meta": "See income, expenses, and profit in one visual dashboard. Monthly cash flow and P&L for small businesses — Google Sheets, instant download.",
        "h1": "Small Business Cash Flow & Profit Dashboard for Google Sheets",
        "ld_desc": "A monthly cash flow and profit dashboard that shows revenue, costs, and net profit at a glance for small businesses, with a simple month-by-month view.",
        "intro": "The Small Business Cash Flow & Profit Dashboard shows the health of your business on one screen. Log your income and expenses by month and the dashboard shows revenue, costs, and net profit at a glance, with the trend over time. It is built for owners who would rather not wrestle with spreadsheets, and works in Google Sheets and Excel.",
        "sections": [
            {"h2": "Monthly Financial Dashboard — Revenue, Costs, and Net Profit at a Glance",
             "body": "Enter your income and costs for each month and the dashboard does the rest: total revenue, total expenses, and the net profit that is left, shown clearly with a month-by-month trend. Instead of digging through rows of transactions, you get the three numbers that actually matter, updated the moment you type."},
            {"h2": "Built for Small Business Owners Who Hate Spreadsheets",
             "body": "You do not need to know accounting or build a single formula. The categories, totals, and charts are already wired up — you just fill in the labelled cells. It is the middle ground between a shoebox of receipts and full accounting software: organised enough to trust, simple enough to actually keep up with. Use it as a clear management view of your month, not a formal financial statement."},
        ],
        "includes": [
            "Monthly income and expense entry by category",
            "Automatic revenue, cost, and net-profit totals",
            "Month-by-month profit trend chart",
            "Clean dashboard summary at the top of the sheet",
            "Editable categories to match your business",
            "No formulas to build — just type your numbers",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "Is this a profit and loss statement?",
             "a": "It is a simple, management-style P&L and cash view rolled into one dashboard — revenue, costs, and net profit by month. It is meant as a clear picture of how the business is doing, not a formal financial statement for filing."},
            {"q": "Do I need accounting knowledge to use it?",
             "a": "No. The categories, totals, and charts are already built. You only type your income and expenses into the labelled cells and the dashboard updates on its own."},
            {"q": "How is this different from the 13-week cash flow forecast?",
             "a": "This dashboard looks back at how each month actually performed. The 13-week forecast looks forward, projecting cash week by week. Many businesses use the dashboard for the monthly picture and the forecast for short-term planning."},
            {"q": "Does it work in Google Sheets?",
             "a": "Yes. It opens in Excel and imports into Google Sheets, and the totals and charts work the same in both."},
        ],
        "related_intro": "Round out your business toolkit with these templates:",
        "related": ["13-week-cash-flow", "invoice-tracker", "expense-tax-tracker"],
    },
    # ------------------------------------------------------------------ 12
    {
        "name": "digital-product-sales-tracker",
        "slug": "zxjrf",
        "price": "19",
        "cat": "Creators",
        "title": "Digital Product Sales Tracker — Google Sheets & Excel",
        "meta": "Track sales, refunds, and revenue across all your digital products in one spreadsheet. See your bestsellers and real profit — Google Sheets and Excel.",
        "h1": "Digital Product Sales Tracker for Google Sheets and Excel",
        "ld_desc": "A digital product sales tracker that records sales, refunds, and net revenue across all your products and shows which ones actually sell.",
        "intro": "The Digital Product Sales Tracker brings every product's numbers into one spreadsheet. Log sales and refunds across all your digital products and the tracker shows net revenue, your bestsellers, and your real profit. It is built for course creators and digital sellers, and works in Google Sheets and Excel.",
        "sections": [
            {"h2": "See Which Products Actually Sell",
             "body": "When you sell across several platforms it is hard to know which products are pulling their weight. The tracker ranks your products by units sold and revenue, so your bestsellers — and your quiet performers — become obvious. That tells you what to promote more and what to retire."},
            {"h2": "Track Sales, Refunds, and Net Revenue",
             "body": "Gross sales alone overstate how you are doing. The tracker logs refunds alongside sales and calculates net revenue, so the figure you act on is the money you actually kept. You can see net revenue per product and across your whole catalogue at a glance."},
            {"h2": "Built for Course Creators and Digital Sellers",
             "body": "Whether you sell courses, templates, presets, or ebooks, the tracker adapts to your catalogue. Add a product, log its sales and refunds, and it folds into your totals — giving you one honest view of your digital business instead of separate numbers scattered across platforms."},
        ],
        "includes": [
            "One row per product with units sold and revenue",
            "Refund logging and automatic net-revenue calculation",
            "Bestseller ranking by units and by revenue",
            "Catalogue-wide totals for sales, refunds, and net revenue",
            "Editable product list for any digital catalogue",
            "Clean summary view of your whole digital business",
            "Works in Google Sheets and Microsoft Excel",
        ],
        "faq": [
            {"q": "Can I track products sold on different platforms?",
             "a": "Yes. You log each product and its sales and refunds in one place regardless of where it sold, so you get a single combined view instead of separate numbers on each platform."},
            {"q": "Does it account for refunds?",
             "a": "Yes. Refunds are logged alongside sales and subtracted automatically, so the net-revenue figure reflects the money you actually kept rather than gross sales."},
            {"q": "Who is this tracker for?",
             "a": "It is built for course creators and digital sellers — anyone selling courses, templates, presets, ebooks, or similar products who wants one clear view of what sells and what they really earned."},
            {"q": "Does it work in Google Sheets?",
             "a": "Yes. It opens in Excel and imports into Google Sheets, and the rankings and net-revenue totals work the same in both."},
        ],
        "related_intro": "More templates for creators and sellers:",
        "related": ["crm-sales-pipeline", "freelancer-tax-estimator", "inventory-reorder"],
    },
]

# Quick lookup by URL-folder name (used for related-link titles).
BY_NAME = {p["name"]: p for p in PRODUCTS}

# Short human title for related-link anchors (kept distinct from the long H1).
SHORT_TITLES = {
    "free-money-tracker": "Free Monthly Money Tracker",
    "monthly-budget-planner": "Monthly Budget Planner",
    "debt-payoff-tracker": "Debt Payoff Tracker",
    "savings-goal-tracker": "Savings Goal Tracker",
    "13-week-cash-flow": "13-Week Cash Flow Forecast",
    "invoice-tracker": "Invoice Tracker & Generator",
    "freelancer-tax-estimator": "Freelancer Tax Estimator",
    "expense-tax-tracker": "Expense & Tax Deduction Tracker",
    "inventory-reorder": "Inventory & Reorder Manager",
    "crm-sales-pipeline": "CRM & Sales Pipeline",
    "cash-flow-profit-dashboard": "Cash Flow & Profit Dashboard",
    "digital-product-sales-tracker": "Digital Product Sales Tracker",
}
